const DA_RECORDS = [
  {
    id: "DA-2026-0419",
    council: "Newcastle",
    suburb: "Wickham",
    address: "18 Railway Lane",
    applicant: "Harbour Quarter Pty Ltd",
    type: "Multi-dwelling",
    value: 38500000,
    lodged: "2026-04-20",
    status: "On exhibition",
    decision: null,
    changedYesterday: true,
    changeType: "New exhibition",
    changeSummary: "Public exhibition opened for a 92-apartment mixed use building near the interchange.",
    lat: -32.922,
    lng: 151.759,
    tags: ["high-value", "multi-dwelling", "commercial"]
  },
  {
    id: "DA-2026-0407",
    council: "Lake Macquarie",
    suburb: "Charlestown",
    address: "310 Pacific Highway",
    applicant: "Northcare Health Group",
    type: "Medical",
    value: 12400000,
    lodged: "2026-04-18",
    status: "Under assessment",
    decision: null,
    changedYesterday: true,
    changeType: "Value changed",
    changeSummary: "Estimated cost increased after amended basement and clinical fitout documents.",
    lat: -32.965,
    lng: 151.693,
    tags: ["high-value", "medical"]
  },
  {
    id: "DA-2026-0398",
    council: "Maitland",
    suburb: "East Maitland",
    address: "7 Fieldsend Street",
    applicant: "Valley Living Co",
    type: "Childcare",
    value: 2850000,
    lodged: "2026-04-22",
    status: "Lodged",
    decision: null,
    changedYesterday: true,
    changeType: "New application",
    changeSummary: "New 96-place childcare centre lodged with basement parking and outdoor play areas.",
    lat: -32.75,
    lng: 151.588,
    tags: ["childcare"]
  },
  {
    id: "DA-2026-0375",
    council: "Cessnock",
    suburb: "Nulkaba",
    address: "Wine Country Drive",
    applicant: "Hunter Stays",
    type: "Tourism",
    value: 9700000,
    lodged: "2026-04-12",
    status: "Under assessment",
    decision: null,
    changedYesterday: false,
    changeType: null,
    changeSummary: null,
    lat: -32.803,
    lng: 151.354,
    tags: ["high-value", "commercial"]
  },
  {
    id: "DA-2026-0362",
    council: "Port Stephens",
    suburb: "Nelson Bay",
    address: "46 Magnus Street",
    applicant: "Bayline Holdings",
    type: "Commercial",
    value: 16800000,
    lodged: "2026-04-08",
    status: "Determined",
    decision: "Approved",
    changedYesterday: true,
    changeType: "Determination",
    changeSummary: "Approved with conditions for ground-floor retail and 38 serviced apartments.",
    lat: -32.72,
    lng: 152.143,
    tags: ["high-value", "commercial"]
  },
  {
    id: "DA-2026-0334",
    council: "Newcastle",
    suburb: "Merewether",
    address: "24 Ridge Street",
    applicant: "Coastal Homes NSW",
    type: "Demolition",
    value: 680000,
    lodged: "2026-04-06",
    status: "Determined",
    decision: "Approved",
    changedYesterday: false,
    changeType: null,
    changeSummary: null,
    lat: -32.945,
    lng: 151.744,
    tags: ["demolition"]
  },
  {
    id: "DA-2026-0310",
    council: "Lake Macquarie",
    suburb: "Boolaroo",
    address: "Main Road Precinct",
    applicant: "Lake Renewal JV",
    type: "Multi-dwelling",
    value: 56500000,
    lodged: "2026-03-28",
    status: "On exhibition",
    decision: null,
    changedYesterday: false,
    changeType: null,
    changeSummary: null,
    lat: -32.954,
    lng: 151.622,
    tags: ["high-value", "multi-dwelling"]
  },
  {
    id: "DA-2026-0292",
    council: "Maitland",
    suburb: "Rutherford",
    address: "12 Mustang Drive",
    applicant: "TradeCo Developments",
    type: "Industrial",
    value: 7400000,
    lodged: "2026-03-21",
    status: "Determined",
    decision: "Approved",
    changedYesterday: true,
    changeType: "Status changed",
    changeSummary: "Moved from under assessment to approved after engineering conditions were added.",
    lat: -32.715,
    lng: 151.526,
    tags: ["commercial"]
  },
  {
    id: "DA-2026-0256",
    council: "Cessnock",
    suburb: "Kurri Kurri",
    address: "98 Lang Street",
    applicant: "Main Street Taverns",
    type: "Pub",
    value: 4100000,
    lodged: "2026-03-12",
    status: "Under assessment",
    decision: null,
    changedYesterday: false,
    changeType: null,
    changeSummary: null,
    lat: -32.818,
    lng: 151.484,
    tags: ["pubs", "commercial"]
  },
  {
    id: "DA-2026-0244",
    council: "Port Stephens",
    suburb: "Raymond Terrace",
    address: "2 Adelaide Street",
    applicant: "Community Housing Hunter",
    type: "Boarding house",
    value: 6100000,
    lodged: "2026-03-06",
    status: "Refused",
    decision: "Refused",
    changedYesterday: true,
    changeType: "Determination",
    changeSummary: "Refused after traffic and neighbourhood character issues were not resolved.",
    lat: -32.762,
    lng: 151.744,
    tags: ["boarding houses"]
  },
  {
    id: "DA-2026-0211",
    council: "Newcastle",
    suburb: "Hamilton",
    address: "118 Beaumont Street",
    applicant: "Beaumont Works",
    type: "Commercial",
    value: 3200000,
    lodged: "2026-02-24",
    status: "Determined",
    decision: "Approved",
    changedYesterday: false,
    changeType: null,
    changeSummary: null,
    lat: -32.922,
    lng: 151.747,
    tags: ["commercial"]
  },
  {
    id: "DA-2026-0188",
    council: "Lake Macquarie",
    suburb: "Belmont",
    address: "9 Gen Street",
    applicant: "Belmont Living",
    type: "Multi-dwelling",
    value: 18400000,
    lodged: "2026-02-14",
    status: "Determined",
    decision: "Approved",
    changedYesterday: false,
    changeType: null,
    changeSummary: null,
    lat: -33.037,
    lng: 151.66,
    tags: ["high-value", "multi-dwelling"]
  },
  {
    id: "DA-2026-0156",
    council: "Maitland",
    suburb: "Thornton",
    address: "Glenwood Drive",
    applicant: "Everyday Retail",
    type: "Commercial",
    value: 9800000,
    lodged: "2026-01-30",
    status: "On exhibition",
    decision: null,
    changedYesterday: false,
    changeType: null,
    changeSummary: null,
    lat: -32.783,
    lng: 151.636,
    tags: ["commercial", "high-value"]
  },
  {
    id: "DA-2025-1120",
    council: "Port Stephens",
    suburb: "Salamander Bay",
    address: "Bagnalls Beach Road",
    applicant: "Aged Care Partners",
    type: "Medical",
    value: 22600000,
    lodged: "2025-12-11",
    status: "Under assessment",
    decision: null,
    changedYesterday: false,
    changeType: null,
    changeSummary: null,
    lat: -32.729,
    lng: 152.08,
    tags: ["medical", "high-value"]
  },
  {
    id: "DA-2025-1036",
    council: "Cessnock",
    suburb: "Branxton",
    address: "35 Maitland Street",
    applicant: "Upper Hunter Homes",
    type: "Multi-dwelling",
    value: 7200000,
    lodged: "2025-11-24",
    status: "Determined",
    decision: "Approved",
    changedYesterday: false,
    changeType: null,
    changeSummary: null,
    lat: -32.657,
    lng: 151.351,
    tags: ["multi-dwelling"]
  }
];
